apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-api-secret
data:
    Mongo__User: {{ .Values.mongodb.auth.usernames | b64enc | quote }}
    Mongo__Password: {{ .Values.mongodb.auth.passwords | b64enc | quote }}